### ISSUE TITLE
Hello, bro, what module logic?

### ISSUE THREAD

**Issue by Juranik** [dubverse-ai/rvc-data-prep#1]
I tried import from utils import clean, but it is not working :(, what I need do? How can I use it? Pls help me, bro

```
Traceback (most recent call last):
  File "C:\Users\Administrator\PycharmProjects\rvc-data-prep\separator.py", line 1, in <module>
    from logic import clean
ModuleNotFoundError: No module named 'logic'

Process finished with exit code 1
```

**Comment by pursuitcurves** [comment]
Sorry bro - made a typo in the README. 

``` python
from utils import clean
```

https://colab.research.google.com/drive/1NA2GuJ2y-zRfoG3NearNiMCQa8NbidSh?usp=sharing
has usage instructions as well.

**Comment by Juranik** [comment]
Big thanks! 
Btw, bro, can u do this version on gradio, that be able use via API this such good vocal separator?
