### ISSUE TITLE
Launch rvc-data-prep in local

### ISSUE THREAD

**Issue by Rudy34160** [dubverse-ai/rvc-data-prep#2]
The project does not work locally after import from github?

I did this, but what next?

![image](https://github.com/dubverse-ai/rvc-data-prep/assets/118270456/b3b534c2-d076-43de-a26e-a297e92a21ca)

**Comment by pursuitcurves** [comment]
<img width="677" alt="image" src="https://github.com/dubverse-ai/rvc-data-prep/assets/33093945/5540cdbd-e6aa-4e77-8531-1afcd5becc52">

there's a comprehensive documentation on how to use this locally. Is there a specific issue you're facing?
